# Generated by Django 5.0.3 on 2024-04-06 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0002_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copiadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('Tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporte.tipo')),
            ],
        ),
    ]
