# Generated by Django 5.0.3 on 2024-04-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0005_alter_copiadora_bandeja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacipon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=100)),
                ('dirrecion', models.CharField(max_length=100)),
            ],
        ),
    ]
