# Generated by Django 5.0.3 on 2024-04-06 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0006_ubicacipon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ubicacipon',
            new_name='Ubicacion',
        ),
    ]
