# Generated by Django 5.0.3 on 2024-04-06 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0007_rename_ubicacipon_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo_Sitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=100)),
                ('encargado', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('libreta', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporte.cliente')),
                ('copiadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporte.copiadora')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporte.ubicacion')),
            ],
        ),
    ]
